### PR TITLE
Fix strings-as-labels for prometheus remote write

### PR DESCRIPTION
**Pull request by Sparc0**
Fix for #646

### CODE REVIEW

**Comment by karimra** [comment]
@Sparc0 this project moved to [`openconfig/gnmic`](https://github.com/openconfig/gnmic) and will soon be archived, Feel free to open a PR there. I will be happy to merge it.

**Comment by Sparc0** [comment]
Ah will do that right away.

**Comment by Sparc0** [comment]
https://github.com/openconfig/gnmic/pull/4

**Comment by karimra** [comment]
on it, thanks!

**Pull request closed without merging**
